#!/usr/bin/env python3
"""
TerraForge Project Scaffolder

Generates a new TerraForge project directory with a ready-to-use main.tf,
.gitignore, and README.

Usage:
    python3 scripts/terraforge_scaffold.py my-project
    python3 scripts/terraforge_scaffold.py my-project --base-url https://api.example.com --endpoint /api/v1/data
    python3 scripts/terraforge_scaffold.py my-project --base-url https://api.example.com --endpoint /api/v1/data --method POST
    python3 scripts/terraforge_scaffold.py my-project --provider local   # local files only, no API
"""

import argparse
import os
import sys
import textwrap


def create_main_tf_rest(base_url, api_key_placeholder, endpoint, method):
    """Generate a main.tf for a REST API provider."""
    return textwrap.dedent(f"""\
        # TerraForge Configuration
        # Docs: references/provider-guide.md

        # ---- Provider: API connection details ----
        provider "rest_api" {{
            base_url = "{base_url}"
            api_key  = "{api_key_placeholder}"
        }}

        # ---- Resource: what to fetch/send ----
        resource "rest_api_resource" "data" {{
            endpoint = "{endpoint}"
            method   = "{method}"
        }}
    """)


def create_main_tf_local(project_name):
    """Generate a main.tf for the local provider."""
    safe_name = project_name.replace("-", "_")
    return textwrap.dedent(f"""\
        # TerraForge Configuration (Local Resources)
        # No API needed -- creates files and directories on your machine.

        provider "local" {{}}

        resource "local_directory" "{safe_name}_dir" {{
            path = "output/{safe_name}"
        }}

        resource "local_file" "{safe_name}_readme" {{
            filename = "output/{safe_name}/README.md"
            content  = "# {project_name}\\nGenerated by TerraForge."
        }}
    """)


def create_gitignore():
    return textwrap.dedent("""\
        # TerraForge
        terraforge.tfstate
        terraforge.tfstate.backup
        data/
        logs/
        output/
        terraforge_export.json

        # Python
        __pycache__/
        *.pyc
        .venv/
    """)


def create_readme(project_name, provider_type):
    return textwrap.dedent(f"""\
        # {project_name}

        TerraForge project ({provider_type} provider).

        ## Quick Start

        ```bash
        terraforge init
        terraforge plan
        terraforge apply --auto
        ```

        ## Commands

        | Command               | Purpose                          |
        |-----------------------|----------------------------------|
        | `terraforge init`     | Initialize and validate config   |
        | `terraforge plan`     | Preview changes (dry run)        |
        | `terraforge apply`    | Execute the plan                 |
        | `terraforge show`     | Inspect current state            |
        | `terraforge destroy`  | Undo all changes                 |
        | `terraforge doctor`   | Diagnose issues                  |
        | `terraforge export`   | Export data for offline use       |

        ## Files

        - `main.tf` -- configuration
        - `terraforge.tfstate` -- state tracking (auto-generated, do not edit)
        - `data/` -- collected API responses
        - `logs/` -- request/response logs
    """)


def main():
    parser = argparse.ArgumentParser(description="Scaffold a new TerraForge project")
    parser.add_argument("name", help="Project directory name")
    parser.add_argument("--base-url", default="https://jsonplaceholder.typicode.com",
                        help="API base URL (default: JSONPlaceholder)")
    parser.add_argument("--api-key", default="YOUR_API_KEY_HERE",
                        help="API key placeholder value")
    parser.add_argument("--endpoint", default="/posts",
                        help="API endpoint path (default: /posts)")
    parser.add_argument("--method", default="GET", choices=["GET", "POST", "PUT", "DELETE"],
                        help="HTTP method (default: GET)")
    parser.add_argument("--provider", default="rest_api", choices=["rest_api", "local"],
                        help="Provider type (default: rest_api)")
    parser.add_argument("--output-dir", default=".",
                        help="Parent directory for the new project (default: current dir)")

    args = parser.parse_args()

    project_path = os.path.join(args.output_dir, args.name)

    if os.path.exists(project_path):
        print(f"[ERROR] Directory already exists: {project_path}")
        sys.exit(1)

    os.makedirs(project_path)

    # main.tf
    if args.provider == "local":
        tf_content = create_main_tf_local(args.name)
    else:
        tf_content = create_main_tf_rest(args.base_url, args.api_key, args.endpoint, args.method)

    with open(os.path.join(project_path, "main.tf"), "w") as f:
        f.write(tf_content)

    # .gitignore
    with open(os.path.join(project_path, ".gitignore"), "w") as f:
        f.write(create_gitignore())

    # README.md
    with open(os.path.join(project_path, "README.md"), "w") as f:
        f.write(create_readme(args.name, args.provider))

    print(f"[OK] Created project: {project_path}")
    print(f"     main.tf       -- {args.provider} provider config")
    print(f"     .gitignore    -- standard ignores")
    print(f"     README.md     -- quick start guide")
    print()
    print(f"Next steps:")
    print(f"  cd {args.name}")
    print(f"  terraforge init")
    print(f"  terraforge plan")
    print(f"  terraforge apply --auto")


if __name__ == "__main__":
    main()
